# -*- coding: utf-8 -*-
"""BERT_FAISS_V1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeJS_KjxBPwy6FY4m9mVtd3SLP64srI2
"""

!pip install transformers torch faiss-cpu datasets pandas numpy tqdm

import torch
import numpy as np
import pandas as pd
from tqdm import tqdm
from transformers import BertTokenizer, BertModel
import faiss

class Config:
    MODEL_NAME = "bert-base-multilingual-cased"
    MAX_SEQ_LENGTH = 128                           # max tokens per sentence
    EMBEDDING_DIM = 768                            # hidden size of BERT base
    SIMILARITY_THRESHOLD = 0.8                     # θ in the proposal
    TOP_K = 5                                      # number of neighbours to retrieve
    BATCH_SIZE = 32                                # for batch embedding
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Using device: {Config.DEVICE}")

tokenizer = BertTokenizer.from_pretrained(Config.MODEL_NAME)
model = BertModel.from_pretrained(Config.MODEL_NAME)
model = model.to(Config.DEVICE)
model.eval()

print(f"Loaded {Config.MODEL_NAME}  —  {sum(p.numel() for p in model.parameters()):,} parameters")

# Each entry needs: "text" (English or Bengali) and "disaster_tag" (one of 18 categories).

sample_data = [
    # --- English examples ---
    {"text": "Massive earthquake strikes the coastal region, buildings collapsed.",           "disaster_tag": "Earthquake"},
    {"text": "Severe flooding reported in the northern districts after heavy rainfall.",      "disaster_tag": "Flood"},
    {"text": "Cyclone warning issued for the Bay of Bengal, wind speeds over 150 km/h.",     "disaster_tag": "Cyclone"},
    {"text": "Forest fire spreads across 500 acres in the hillside area.",                   "disaster_tag": "Wildfire"},
    {"text": "Landslide buries several homes in the mountainous village.",                   "disaster_tag": "Landslide"},
    {"text": "Tsunami alert after 7.2 magnitude undersea earthquake.",                       "disaster_tag": "Tsunami"},
    {"text": "Drought conditions worsen, crops failing across the southern province.",        "disaster_tag": "Drought"},
    {"text": "Volcanic eruption forces evacuation of nearby towns.",                         "disaster_tag": "Volcanic Eruption"},
    {"text": "Heatwave kills dozens as temperatures exceed 48 degrees Celsius.",             "disaster_tag": "Heatwave"},
    {"text": "Tornado tears through the village leaving massive destruction.",               "disaster_tag": "Tornado"},
    {"text": "Building collapse traps workers at the construction site.",                    "disaster_tag": "Building Collapse"},
    {"text": "Heavy snowfall causes avalanche in the northern mountains.",                   "disaster_tag": "Avalanche"},
    {"text": "Oil spill from tanker threatens marine life along the coast.",                 "disaster_tag": "Oil Spill"},
    {"text": "Bridge washed away as river water levels rise dangerously.",                   "disaster_tag": "Flood"},
    {"text": "Lightning strike causes fire in residential neighbourhood.",                   "disaster_tag": "Lightning"},
    {"text": "Hundreds displaced after riverbank erosion in the delta region.",              "disaster_tag": "Riverbank Erosion"},
    {"text": "Gas leak at the chemical plant triggers emergency evacuation.",                "disaster_tag": "Industrial Accident"},
    {"text": "Storm surge inundates low-lying areas near the coast.",                        "disaster_tag": "Storm Surge"},

    # --- Bengali examples (বাংলা) ---
    {"text": "প্রচণ্ড ভূমিকম্পে উপকূলীয় এলাকায় ভবন ধসে পড়েছে।",                           "disaster_tag": "Earthquake"},
    {"text": "ভারী বৃষ্টিতে উত্তরাঞ্চলে ভয়াবহ বন্যা দেখা দিয়েছে।",                          "disaster_tag": "Flood"},
    {"text": "বঙ্গোপসাগরে ঘূর্ণিঝড়ের সতর্কতা জারি, বাতাসের গতি ১৫০ কিমি/ঘণ্টার বেশি।",    "disaster_tag": "Cyclone"},
    {"text": "পাহাড়ি এলাকায় দাবানল ৫০০ একর জুড়ে ছড়িয়ে পড়েছে।",                           "disaster_tag": "Wildfire"},
    {"text": "পাহাড়ি গ্রামে ভূমিধসে বেশ কয়েকটি বাড়ি চাপা পড়েছে।",                          "disaster_tag": "Landslide"},
    {"text": "সমুদ্রের তলদেশে ৭.২ মাত্রার ভূমিকম্পের পর সুনামি সতর্কতা।",                   "disaster_tag": "Tsunami"},
    {"text": "খরার পরিস্থিতি আরও খারাপ হচ্ছে, দক্ষিণাঞ্চলে ফসল নষ্ট হচ্ছে।",               "disaster_tag": "Drought"},
    {"text": "তীব্র তাপপ্রবাহে তাপমাত্রা ৪৮ ডিগ্রি ছাড়িয়েছে, বহু মানুষ মারা গেছে।",       "disaster_tag": "Heatwave"},
    {"text": "টর্নেডো গ্রামের মধ্য দিয়ে বয়ে গেছে, ব্যাপক ধ্বংসযজ্ঞ হয়েছে।",              "disaster_tag": "Tornado"},
    {"text": "নির্মাণস্থলে ভবন ধসে শ্রমিকরা আটকে পড়েছে।",                                  "disaster_tag": "Building Collapse"},
    {"text": "নদীভাঙনে বদ্বীপ এলাকায় শত শত মানুষ বাস্তুচ্যুত হয়েছে।",                       "disaster_tag": "Riverbank Erosion"},
    {"text": "রাসায়নিক কারখানায় গ্যাস লিকের কারণে জরুরি সরিয়ে নেওয়া হয়েছে।",             "disaster_tag": "Industrial Accident"},
]

df = pd.DataFrame(sample_data)
print(f"Dataset size: {len(df)} sentences across {df['disaster_tag'].nunique()} disaster categories")
print(df["disaster_tag"].value_counts())

# Implements Section 1 of the proposal:
#   H = BERT(X) = {h1, h2, ..., hn}
# Then takes the MEAN of all token embeddings (excluding padding) as the
# fixed-size sentence representation.

def generate_embeddings(sentences: list, batch_size: int = Config.BATCH_SIZE) -> np.ndarray:
    """
    Steps (matching the proposal):
      1. Prepend [CLS], append [SEP]
      2. WordPiece tokenization
      3. Token + Position embeddings (Segment = 0 for single sentences)
      4. 12 self-attention layers
      5. Mean-pool all token embeddings → fixed-size vector
    """
    all_embeddings = []

    for start in tqdm(range(0, len(sentences), batch_size), desc="Embedding"):
        batch = sentences[start : start + batch_size]

        # Tokenization: adds [CLS], [SEP], applies WordPiece
        encoded = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=Config.MAX_SEQ_LENGTH,
            return_tensors="pt",
        )
        encoded = {k: v.to(Config.DEVICE) for k, v in encoded.items()}

        with torch.no_grad():
            outputs = model(**encoded)
            # outputs.last_hidden_state: (batch, seq_len, 768)
            hidden_states = outputs.last_hidden_state

        # Mean pooling over non-padding tokens
        attention_mask = encoded["attention_mask"].unsqueeze(-1)  # (batch, seq_len, 1)
        masked_hidden = hidden_states * attention_mask
        summed = masked_hidden.sum(dim=1)                        # (batch, 768)
        counts = attention_mask.sum(dim=1).clamp(min=1)          # avoid /0
        mean_pooled = (summed / counts).cpu().numpy()

        all_embeddings.append(mean_pooled)

    return np.vstack(all_embeddings).astype("float32")


# Generate embeddings for the full dataset
sentences = df["text"].tolist()
embeddings = generate_embeddings(sentences)
print(f"Embedding matrix shape: {embeddings.shape}")  # (N, 768)

# Implements Section 2 of the proposal:
#   Store (E(S), Tag(S)) pairs; retrieve via ANN with threshold θ = 0.8
#
# We use an Inner-Product index on L2-normalised vectors so that the
# similarity score equals cosine similarity (range 0–1).

def build_faiss_index(embeddings: np.ndarray) -> faiss.IndexFlatIP:
    # L2-normalise so dot product == cosine similarity
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(Config.EMBEDDING_DIM)
    index.add(embeddings)
    print(f"FAISS index built — {index.ntotal} vectors indexed")
    return index


index = build_faiss_index(embeddings.copy())  # copy because normalize_L2 is in-place

# Parallel arrays: index position i → (text, tag)
index_texts = df["text"].tolist()
index_tags = df["disaster_tag"].tolist()

# Given a new query Q:
#   1. Compute E(Q) via BERT
#   2. ANN search in FAISS
#   3. Filter by Similarity(E(Q), E(S_i)) >= θ

def query_disaster(
    query: str,
    top_k: int = Config.TOP_K,
    threshold: float = Config.SIMILARITY_THRESHOLD,
) -> pd.DataFrame:
    # 1. Embed the query
    q_emb = generate_embeddings([query])
    faiss.normalize_L2(q_emb)

    # 2. ANN search
    scores, indices = index.search(q_emb, top_k)
    scores = scores[0]
    indices = indices[0]

    # 3. Apply similarity threshold
    results = []
    for score, idx in zip(scores, indices):
        if idx == -1:
            continue
        if score >= threshold:
            results.append({
                "matched_text": index_texts[idx],
                "disaster_tag": index_tags[idx],
                "similarity_score": round(float(score), 4),
            })

    return pd.DataFrame(results)

# English query
print("=" * 80)
print("QUERY (English): 'A strong tremor shook the city and several buildings crumbled.'")
print("=" * 80)
results = query_disaster("A strong tremor shook the city and several buildings crumbled.")
print(results.to_string(index=False))

print()

# Bengali query
print("=" * 80)
print("QUERY (Bengali): 'প্রচণ্ড বন্যায় হাজার হাজার মানুষ গৃহহীন হয়ে পড়েছে।'")
print("=" * 80)
results = query_disaster("প্রচণ্ড বন্যায় হাজার হাজার মানুষ গৃহহীন হয়ে পড়েছে।")
print(results.to_string(index=False))

print()

# Mixed / edge case
print("=" * 80)
print("QUERY: 'Gas explosion at the factory injured 20 workers.'")
print("=" * 80)
results = query_disaster("Gas explosion at the factory injured 20 workers.")
print(results.to_string(index=False))

def predict_disaster_tag(query: str, top_k: int = Config.TOP_K, threshold: float = Config.SIMILARITY_THRESHOLD) -> dict:
    """
    Predict the disaster category using weighted majority vote
    among retrieved neighbours.
    """
    results = query_disaster(query, top_k=top_k, threshold=threshold)

    if results.empty:
        return {"predicted_tag": "Unknown / No Match", "confidence": 0.0, "details": results}

    # Weighted majority vote by similarity score
    weighted = results.groupby("disaster_tag")["similarity_score"].sum()
    predicted_tag = weighted.idxmax()
    confidence = weighted.max() / weighted.sum()

    return {
        "predicted_tag": predicted_tag,
        "confidence": round(confidence, 4),
        "details": results,
    }


# Test predictions
test_sentences = [
    "The river overflowed and submerged the entire village.",
    "প্রচণ্ড ঝড়ে গাছ উপড়ে পড়েছে এবং বিদ্যুৎ লাইন ছিঁড়ে গেছে।",
    "Massive wildfire raging through the national park.",
    "ভূমিকম্পে রাস্তায় বড় ফাটল দেখা দিয়েছে।",
]

for sent in test_sentences:
    result = predict_disaster_tag(sent)
    print(f"\nInput : {sent}")
    print(f"Tag   : {result['predicted_tag']}  (confidence: {result['confidence']})")
    print(result["details"].to_string(index=False))
    print("-" * 80)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import seaborn as sns
import matplotlib.pyplot as plt

test_data = [
    # English
    {"text": "A powerful quake destroyed homes and roads in the capital.",                    "true_tag": "Earthquake"},
    {"text": "Floodwaters have submerged farmland across three districts.",                   "true_tag": "Flood"},
    {"text": "The cyclone made landfall with devastating wind and rain.",                     "true_tag": "Cyclone"},
    {"text": "Uncontrolled bush fire threatens nearby settlements.",                          "true_tag": "Wildfire"},
    {"text": "A hillside collapsed burying houses under mud and debris.",                     "true_tag": "Landslide"},
    {"text": "Coastal areas evacuated after tsunami warning was issued.",                     "true_tag": "Tsunami"},
    {"text": "Months without rain have dried up reservoirs and wells.",                       "true_tag": "Drought"},
    {"text": "Lava flowing from the volcano has reached the town border.",                   "true_tag": "Volcanic Eruption"},
    {"text": "Record-breaking temperatures send hundreds to hospital.",                      "true_tag": "Heatwave"},
    {"text": "A violent tornado ripped roofs off houses in the suburb.",                      "true_tag": "Tornado"},
    {"text": "Multi-storey building collapsed during the morning rush.",                     "true_tag": "Building Collapse"},
    {"text": "Snow avalanche blocks the highway in the mountain pass.",                      "true_tag": "Avalanche"},
    {"text": "Crude oil leak from the pipeline pollutes the river.",                         "true_tag": "Oil Spill"},
    {"text": "Lightning struck a power station causing widespread outage.",                  "true_tag": "Lightning"},
    {"text": "Erosion along the riverbank has swallowed several houses.",                    "true_tag": "Riverbank Erosion"},
    {"text": "Chemical plant explosion releases toxic fumes into the air.",                  "true_tag": "Industrial Accident"},
    {"text": "Tidal surge flooded coastal villages overnight.",                              "true_tag": "Storm Surge"},

    # Bengali
    {"text": "রাজধানীতে শক্তিশালী ভূমিকম্পে বাড়িঘর ও রাস্তা ধ্বংস হয়েছে।",                "true_tag": "Earthquake"},
    {"text": "তিনটি জেলায় বন্যার পানিতে কৃষিজমি তলিয়ে গেছে।",                              "true_tag": "Flood"},
    {"text": "ঘূর্ণিঝড় প্রচণ্ড বাতাস ও বৃষ্টি নিয়ে উপকূলে আঘাত হেনেছে।",                  "true_tag": "Cyclone"},
    {"text": "অনিয়ন্ত্রিত দাবানল আশেপাশের জনবসতি হুমকিতে ফেলেছে।",                         "true_tag": "Wildfire"},
    {"text": "পাহাড়ধস হয়ে কাদা ও ধ্বংসাবশেষের নিচে বাড়ি চাপা পড়েছে।",                    "true_tag": "Landslide"},
    {"text": "সুনামি সতর্কতায় উপকূলীয় এলাকা থেকে মানুষ সরিয়ে নেওয়া হচ্ছে।",              "true_tag": "Tsunami"},
    {"text": "মাসের পর মাস বৃষ্টি না হওয়ায় জলাশয় শুকিয়ে গেছে।",                            "true_tag": "Drought"},
    {"text": "রেকর্ড তাপমাত্রায় শত শত মানুষ হাসপাতালে ভর্তি হয়েছে।",                       "true_tag": "Heatwave"},
    {"text": "টর্নেডোতে শহরতলির বাড়ির ছাদ উড়ে গেছে।",                                     "true_tag": "Tornado"},
    {"text": "বহুতল ভবন ধসে সকালের ভিড়ের সময় মানুষ আটকে পড়েছে।",                          "true_tag": "Building Collapse"},
    {"text": "নদীতীরের ভাঙনে বেশ কয়েকটি বাড়ি নদীতে বিলীন হয়েছে।",                         "true_tag": "Riverbank Erosion"},
    {"text": "রাসায়নিক কারখানায় বিস্ফোরণে বিষাক্ত ধোঁয়া ছড়িয়ে পড়েছে।",                  "true_tag": "Industrial Accident"},
]

# --------------------------------------------------------------------------
# Run predictions on the test set
# --------------------------------------------------------------------------
y_true = []
y_pred = []

print("Running predictions on test set...\n")
for item in tqdm(test_data, desc="Evaluating"):
    result = predict_disaster_tag(item["text"])
    y_true.append(item["true_tag"])
    y_pred.append(result["predicted_tag"])

# --------------------------------------------------------------------------
# Classification Report: Precision, Recall, F1-Score per class + Accuracy
# --------------------------------------------------------------------------
print("\n" + "=" * 80)
print("CLASSIFICATION REPORT")
print("=" * 80)
report = classification_report(y_true, y_pred, zero_division=0)
print(report)

accuracy = accuracy_score(y_true, y_pred)
print(f"Overall Accuracy: {accuracy:.4f}  ({sum(t == p for t, p in zip(y_true, y_pred))}/{len(y_true)} correct)")

# --------------------------------------------------------------------------
# Save report as a DataFrame (for export / further analysis)
# --------------------------------------------------------------------------
report_dict = classification_report(y_true, y_pred, output_dict=True, zero_division=0)
report_df = pd.DataFrame(report_dict).transpose()
print("\n" + "=" * 80)
print("METRICS TABLE")
print("=" * 80)
print(report_df.to_string())

# --------------------------------------------------------------------------
# Confusion Matrix Heatmap
# --------------------------------------------------------------------------
labels = sorted(set(y_true + y_pred))
cm = confusion_matrix(y_true, y_pred, labels=labels)

plt.figure(figsize=(14, 10))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=labels,
    yticklabels=labels,
)
plt.xlabel("Predicted Tag")
plt.ylabel("True Tag")
plt.title("Confusion Matrix — Disaster Detection")
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()